### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by pribadihcr** [InnovArul/personreid_normxcorr#1]
Hi @InnovArul 

Where are the train and test source code?. 

Thanks,
 rchip

**Comment by InnovArul** [comment]
code is available now. 
The readme file will be available by next week.
Hope, it helps.

**Comment by InnovArul** [comment]
All of the code files are checked-in and a readme file is available. 
Hope it helps.

**Comment by pribadihcr** [comment]
Hi @InnovArul 

Thank you very much, try it later.
