### ISSUE TITLE
Running Issues

### ISSUE THREAD

**Issue by EthanPKU** [InnovArul/personreid_normxcorr#2]
when executing the file 'doall.lua', issues occurs as below. Could anyone help?
![image](https://cloud.githubusercontent.com/assets/16401418/21140858/1dfe7a40-c175-11e6-83e6-a6301283ad43.png)

**Comment by InnovArul** [comment]
Hi @EthanPKU ,
I do not remember such types of error. The uploaded snapshot does not reveal the full variable name. Can you please upload a snapshot with full variable name?

**Comment by InnovArul** [comment]
Hope, you had sorted out the solutions. Please get back if you need any help.

**Comment by EthanPKU** [comment]
Issues were solved by commenting some logger.trace sentence... strange though..
