### ISSUE TITLE
CMC score

### ISSUE THREAD

**Issue by pribadihcr** [InnovArul/personreid_normxcorr#3]
Hi @InnovArul ,

How do you get the CMC score for ranking. 
Generally, the first rank is the lowest dissimilarity score and so on. Does the dissimilarity score get from the probability of softmax otuput ?

Thanks

**Comment by InnovArul** [comment]
Hi @pribadihcr ,

Yes. You are right. The softmax output score (can be either from 'same' (or) 'different' softmax node) is used for CMC ranking calculations.

**Comment by pribadihcr** [comment]
For ex: there is three probe images & three images in gallery
probe: person-Ap, person-Bp, person-Cp
gallery: person-Ag, person-Bg, person-Cg

in the prediction:
person-Ap & person-Ag, the output softmax = 1 (true prediction)
person-Ap & person-Bg, the output softmax also 1 (false prediction, the ground truth is 0).
person-Ap & person-Cg, the output softmax is 0 (true prediction)
So, what is the rank of person-Ap & person-Ag.
Thanks.

**Comment by InnovArul** [comment]
Please note that the softmax score may never be exactly 1. i.e., it shall be a floating point score. Further, we are making use of 'Log' of softmax scores.

In CMC (Cumulative Matching Characteristics) calculation, 

1. a particular probe image (which belongs to Identity 'X') is compared with 'G' gallery images and similarity scores are retrieved. 
2. The scores are sorted in descending order (to be arranged in Highest to Lowest **similarity** score order)
3. Ideally, in the sorted scores, we would expect the score of gallery image w.r.t Identity 'X' to be at first. 
if that's the case, then we got a rank-1 match. Or else, find the index 'i' of gallery image of Identity X's score in the sorted list and then, we have a rank-i match.

Hope, it helps.
