### ISSUE TITLE
size of target images

### ISSUE THREAD

**Issue by pribadihcr** [InnovArul/personreid_normxcorr#4]
Hi @InnovArul,

For example in CUHK03 dataset. For testing, there is 100 identities in gallery images.
How about for probe images. I guess the probe images is not 100 identities. Because, if the size is 100, so, there is 100x100, and there are no values behind commas for the CMC score.

Thanks

**Comment by InnovArul** [comment]
As per single-shot test procedure, a single gallery image is selected for each individual and the remaining images are added to probe set. As per the CUHK03 example, there shall be 100 gallery images and the remaining images in all the identities shall be added to probe set.
Please refer to the book[1], relevant paper[2] for more details.

Sorry that I did not understand what you meant by "and there are no values behind commas for the CMC score".

[1] Gong, Shaogang, Marco Cristani, Shuicheng Yan, and Chen Change Loy. Person re-identification. Vol. 1. London: Springer, 2014.
[2] Li, Wei, et al. "Deepreid: Deep filter pairing neural network for person re-identification." Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2014.

**Comment by pribadihcr** [comment]
Thanks.
